seta:
  urls:
    seta-analysis-api-url: "http://localhost:5000"
    seta-notification-api-url: "http://localhost:10001"
spring:
  application:
    name: seta-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allowed-origin-patterns:
              - "*"
            allow-credentials: true
server:
  port: 10000
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE